vanetza/security/region.cpp, vanetza/security/region.hpp, vanetza/security/tests/region.cpp
Exact matches are trivially within themselves. The implementation of this was surprisingly easy, I hope it's right that way.
=> security: Implement is_within for exact matches

tools/socktap/main_bench_in.cpp
This only affects the bench-in variant.
=> socktap: Disable security if no trusted certificates are given

vanetza/btp/ports.hpp
Hi Raphael,
in ETSI TS 103 248 V1.3.1 (2019-04) there are a couple of new BTP ports defined. This PR adds them to vanetza.
Note: The names of the according variables resembled the names of the messages rather than the names of the services before. I stuck to that pattern to keep it consistent. The downside is that there are now five different variables for port 2011 - one for each message of the TPG service.
The other option would be to name the ports after the services but that breaks backwards compatibility and is not nice because the TLC has two messages with different ports for the two different messages.
I found the current solution the better trade-off but am happy to change it if you prefer the second option.
Best regards
Keno
=> Update BTP port numbers to latest version of the standard

tools/socktap/cohda.hpp
Plain and simple: the header `cohda.hpp` is missing the include statement for `ethernet_header.hpp`.
=> socktap: add missing include in cohda header

tools/socktap/raw_socket_link.cpp, tools/socktap/raw_socket_link.hpp
Fixes issue to send over Cohda link-layer introduced in f397ab2
=> socktap: add Physical layer to layers send over raw_socket_link

tools/socktap/gps_position_provider.cpp
"altitude" variable is deprecated after GPSD_API_MAJOR_VERSION = 8.
Rather "altHAE" (height above ellipsoid) or "altMSL" (mean sea level) is used.
According to ETSI TS 102 894-2 V1.3.1 (2018-08), height above ellipsoid is used in data frames.
=> socktap: fetch altitude for GPSD_API_MAJOR_VERSION > 8

cmake/FindGeographicLib.cmake
Hi @riebl,
I installed GeographicLib from the Arch User Repository on my system. Unfortunately, it is seems to be named differently now, such that `cmake/FindGeographicLib.cmake` cannot find it anymore.
This small patch adds the name the library has on my system and CMake now finds the library again.
I thought this might help others, too.
Best regards
Keno
=> Adds alternative name for lib to FindGeographiclib

conanfile.py
This PR includes a simple change in conanfile.py. **_requires_** replaced with **_requirements_** method alternative which could provide a better logic if necessary. The versions of the dependencies changed in a way that give the same meaning with CMakeLists.txt find_package versions.  I have also added into the conanfile.py that the build options which are already exist in CMakeLists.txt.
=> conan: same dependency versions in conanfile and cmakelists

docs/tools/socktap.md, tools/socktap/CMakeLists.txt, tools/socktap/link_layer.cpp, tools/socktap/link_layer.hpp, tools/socktap/main.cpp, tools/socktap/tcp_link.cpp, tools/socktap/tcp_link.hpp
I've added TCP to socktap.
To accept incoming connections, use `--tcp-accept 127.0.0.1:12345`.
To connect to another service, use `--tcp-connect 127.0.0.1:12345`.
=> Added TCP LinkLayer to socktap

tools/socktap/autotalks_link.cpp, tools/socktap/autotalks_link.hpp, tools/socktap/link_layer.cpp
I noticed that in Autotalks link layer, sometimes we get the same error as mentioned [here](https://github.com/riebl/vanetza/issues/181#issue-1559609353), so I tried to use `boost::asio::post` as @riebl suggested. This seems to fix the issue but I do not know if it is 100% correct.
=> Use boost::asio::post in asynchronous callback in Autotalks link layer

tools/socktap/gps_position_provider.cpp
The gpsd status field is never set >= 0 despite mode is = 3D in my 3.25 installation. According to https://gitlab.com/gpsd/gpsd/-/issues/183 the status field was never meant to be used for validating the fix.
=> socktap: remove gpsd status field from checks

vanetza/asn1/asn1c_wrapper.cpp, vanetza/asn1/asn1c_wrapper.hpp, vanetza/asn1/tests/asn1c_wrapper.cpp
Adds new `print()` method to ASN.1 types by leveraging asn1c's `asn_fprint()`. 
Defaults to `stdout` though the output stream can be specified. Specifying the output is done through a `FILE*`, since there is no straightforward way to convert between an `std::ostream` to a `FILE*`.
Can be regarded as an alternative to CAM's `print_indented()`.
=> asn1: Add print() method to asn1c wrapper

vanetza/asn1/asn1c_wrapper.cpp, vanetza/asn1/asn1c_wrapper.hpp, vanetza/asn1/tests/asn1c_wrapper.cpp
Adds new `compare()` and related `==` and `!=` overloads to the asn1c wrapper.
Leverages asn1c's `compare_struct` operation, which tests the equality of two ASN.1 structs of the same type.
=> asn1: Add compare methods to asn1c wrapper

vanetza/asn1/asn1c_wrapper.cpp
May I suggest the use of OER to do the roundtrip-based copy of ASN.1 types?
Unless there are any concerns with the implementation/safety of asn1c's OER, we can consider it over the current BER/DER copy since it is much faster.
A benchmark of 1000000 roundrip encoding/decodings of a zero-initialized CAM with some fields set to `1` to pass the constraint checks:
```
OER Roundtrip in 3.370587 s   // (canonical)
BER Roundtrip in 14.393260 s  // der -> ber
PER Roundtrip in 3.833098 s   // (canonical unaligned)
JER Roundtrip in 10.260315 s  // (minified)
XER Roundtrip in 14.103931 s  // (canonical)
```
=> asn1: OER-based copy for asn1c wrapper

vanetza/btp/ports.hpp
Updates the BTP port numbers to the latest release of the standard TS 103 248 v2.3.1 release in March 2024
=> Update ports to newest BTP standard

vanetza/geonet/mib.hpp, vanetza/geonet/router.cpp
ETSI EN 302 636-4-1 v1.4.1 has three itsGnIfType - Unspecified, its-g5 and lte-v2x.
=> Add InterfaceType LTE_V2X

vanetza/security/v2/sign_service.cpp, vanetza/security/v2/signature.hpp, vanetza/security/v3/certificate.cpp, vanetza/security/v3/certificate.hpp, vanetza/security/v3/persistence.cpp, vanetza/security/v3/persistence.hpp
Hi,
couple of small changes:
1. Pretty sure by this - `vanetza::security::v3::save_certificate_to_file()` has `certificate` parameter `const` in header but not `const` in implementation. Adding it there requires that `vanetza::security::v3::serialize()` for certificate has this parameter also `const`. Further, small comment fix.
2. Small cleanup - remove `<future>` header inclusion from `vanetza/security/v2/sign_service.cpp` and `vanetza/security/v2/signature.hpp` as it seems not needed here, just in `vanetza/security/signature.hpp`. This was just for my convenience when building library for C++/CLI wrapper, since that does not support `<future>` and I wanted it in as few places as possible. Please ignore this if you think it is not needed.
=> Small fixes

CMakeLists.txt
Since the Autotalks library is used for only **socktap** tool and is optional, the find operation should be removed from the root `CMakeLists.txt`. I think, it is actually the same case with Cohda libraries' find operation.
=> Removing Autotalks find operation in Root CMakeLists.txt

vanetza/asn1/its/TimestampIts.c, vanetza/asn1/its/TimestampIts.h, vanetza/asn1/its/r2/TimestampIts.c, vanetza/asn1/its/r2/TimestampIts.h, vanetza/asn1/patches/its-64bit-types.patch
Tried to implement aforementioned fix based on https://github.com/riebl/vanetza/blob/master/vanetza/asn1/patches/security-64bit-types.patch - as advised by @riebl in #245.
Raphael, please, I am not sure what does the `asn_INTEGER_specifics_t` structure mean, does it also have to be added here?
=> asn1: patch ITS timestamp for 32-bit targets (see #245)

vanetza/btp/ports.hpp
Update BTP ports to the [new version](https://www.etsi.org/deliver/etsi_ts/103200_103299/103248/02.04.01_60/ts_103248v020401p.pdf).
=> btp: update ports.hpp to TS 103 248 v2.4.1

vanetza/asn1/patches/security-64bit-types.patch, vanetza/asn1/security/r2/Time64.c, vanetza/asn1/security/r2/Time64.h, vanetza/asn1/security/r2/Uint64.c, vanetza/asn1/security/r2/Uint64.h
I noticed that I have some compilation warning and I think that is by missing patch to Release 2 64bit types.
=> asn1: add missing patch for Release 2 64bit types

vanetza/security/CMakeLists.txt, vanetza/security/hmac.cpp, vanetza/security/hmac.hpp, vanetza/security/v3/basic_elements.cpp, vanetza/security/v3/basic_elements.hpp, vanetza/security/v3/certificate.cpp, vanetza/security/v3/certificate.hpp, vanetza/security/v3/trust_store.cpp, vanetza/security/v3/trust_store.hpp, vanetza/security/v3/validity_restriction.cpp, vanetza/security/v3/validity_restriction.hpp
Add v3/ files and HMAC implementation.
Some helpers methods for V3 certificate must be added too or else the build fails.
=> security: add hmac, v3/basic_elements, v3/trust_store, v3/validity_restriction
